### ISSUE TITLE
Can't get to install

### ISSUE THREAD

**Issue by Goofball2** [Harry09/Smooth-Interior-Camera#2]
I have made a folder in bin, copied the .dll file into it. The plugin doesn't load in my ETS2. Please help

**Comment by Harry09** [comment]
Is it a bin/win_x64 or bin/win_x86? Have you copied sic_x64.dll or sic_x86.dll? Did you start as 64 bit or 32 bit?
Also, send `game.log.txt` which is located in Documents/Euro Truck Simulator 2.

**Comment by Goofball2** [comment]
Hi, I managed to get it to work. Had to restart the game for some reason then it worked. Fantastic plugin/mod!
